#!/usr/bin/env python
# Print your external IP address to stdout

import urllib

def main():
   data = urllib.urlopen('http://checkip.dyndns.org/').read()
   print data.partition('Address:')[2].partition('<')[0].strip()

if __name__ == '__main__':
    main()

