#!/usr/bin/env python

import sys
import json

INDENT = 4

def main():
    ifs = len(sys.argv) > 1 and open(sys.argv[1]) or sys.stdin
    ofs = len(sys.argv) > 2 and open(sys.argv[2]) or sys.stdout
    ofs.write(json.dumps(json.loads(ifs.read()), indent=INDENT))

if __name__ == '__main__':
    main()
