#!/usr/bin/env python

from colorama import init, Fore
import os
import sys
import subprocess

PATH = os.path.expanduser('~/dev/seeds')
seeds = [dir for dir in os.listdir(PATH) if not dir.startswith('.')]

def avail():
    return 'Available seeds:\n  ' + Fore.CYAN + '\n  '.join(seeds) + Fore.RESET

def main():
    init()
    # Split args
    opts = [arg for arg in sys.argv if arg.startswith('-') or arg.startswith('--')]
    args = [arg for arg in sys.argv if arg not in opts]

    if len(sys.argv) < 2:
        print 'Usage: %s seed [path] (options)' % os.path.basename(sys.argv[0])
        print avail()
        sys.exit()

    seed = sys.argv[1]
    if not seed in seeds:
        print avail()
        sys.exit()
    
    if '--peek' in opts or '-p' in opts:
        subprocess.call(['find ' + os.path.join(PATH, seed)], shell=True)
    else:
        argMsg = ''
        if len(sys.argv) > 2:
            root = sys.argv[2]
            argMsg = ' to ' + Fore.RED + root + Fore.RESET
        else:
            root = os.getcwd()
        subprocess.call(['rsync', '-aW', '--exclude=.*', os.path.join(PATH, seed) + '/', root])
        print 'Expanded seed ' + Fore.RED + seed + Fore.RESET + argMsg

if __name__ == '__main__':
    main()
