#!/usr/bin/env python

# Ultra lightweight web server

import os
import BaseHTTPServer
import mimetypes
import httplib
import errno
import socket

ADDR = ''
PORT = 5000

class MyHandler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.endswith('/'):
            self.path += 'index.html'
        try:
            fh = open(os.path.join(root, self.path[1:]), 'rb')
            self.send_response(httplib.OK)
            self.send_header('Content-Type', mimetypes.guess_type(self.path)[0])
            self.end_headers()
            self.wfile.write(fh.read())
            fh.close()
        except IOError:
            self.send_error(httplib.NOT_FOUND, 'Document not found: %s' % self.path)

if __name__ == '__main__':
    root = os.path.abspath(os.getcwd())
    try:
        server = BaseHTTPServer.HTTPServer((ADDR, PORT), MyHandler)
        print 'Server running at http://127.0.0.1:%s ...' % PORT
        print 'Press CTRL+C to quit'
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            sys.exit()
    except socket.error:
        print 'Unable to bind socket (perhaps another server is running?)'

